### ISSUE TITLE
Enabling Github Template

### ISSUE THREAD

**Issue by shadowtime2000** [excaliburjs/template-ts-webpack#114]
### Context

I want to use this template but I am not too keen on having to fork and clone this repository,

### Proposal

One solution I can think of is enabling this repo as a Github template so people can just click "Use this template"

**Comment by eonarheim** [comment]
@shadowtime2000 for sure, that makes a ton of sense 👍

**Comment by eonarheim** [comment]
@shadowtime2000 Template enabled!
