### ISSUE TITLE
template-ts-webpack: `npm run dev` does not work

### ISSUE THREAD

**Issue by thomergil** [excaliburjs/template-ts-webpack#141]
This is for `template-ts-webpack`.

Two problems.

1. `npm run dev` runs a server on localhost:8080, not on localhost:8082 as the documentation seems to suggest.
2. Navigating to `localhost:8080` yields an `Uncaught TypeError: this.path.indexOf is not a function`; stacktrace suggests this is in `index.ts`, line 31.

Environment: Windows 10, Cygwin, nodejs.org (14.15.3 LTS) install.

**Comment by kamranayub** [comment]
Should be fixed now, thanks for reporting. Looks like the old `require()` call used to work but should have been replaced with ES2015 `import` and corresponding TS declarations.
